name: Deploy Infrastructure and Azure Function

on:
  push:
    branches:
      - main
    paths:
      - 'azure_functions/**'
      - 'terraform/**'
      - '.github/workflows/*.yml'

jobs:
  terraform:
    runs-on: ubuntu-latest

    outputs:
      function_app_name: ${{ steps.get_function_app_name.outputs.function_app_name }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_wrapper: false

    - name: Terraform Init
      run: |
        export ARM_CLIENT_ID=$ARM_CLIENT_ID
        export ARM_CLIENT_SECRET=$ARM_CLIENT_SECRET
        export ARM_SUBSCRIPTION_ID=$ARM_SUBSCRIPTION_ID
        export ARM_TENANT_ID=$ARM_TENANT_ID

        terraform init
      working-directory: ./terraform
      env:
        ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

    - name: Terraform Apply
      id: apply
      run: terraform apply -auto-approve
      working-directory: ./terraform
      env:
        ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        TF_VAR_project_name: "botgcint"
        TF_VAR_environment: "prd"
        TF_VAR_member_id: ${{ secrets.MEMBER_ID }}
        TF_VAR_member_pin: ${{ secrets.MEMBER_PIN }}
        TF_VAR_admin_password: ${{ secrets.ADMIN_PASSWORD }}
        TF_VAR_mailchimp_api_key: ${{ secrets.MAILCHIMP_API_KEY }}
        TF_VAR_mailchimp_server: ${{ secrets.MAILCHIMP_SERVER }}
        TF_VAR_mailchimp_audience_id: ${{ secrets.MAILCHIMP_AUDIENCE_ID }}

    - name: Get Function App Name
      id: get_function_app_name
      run: |
        function_app_name=$(terraform output -raw function_app_name)
        echo "function_app_name=${function_app_name}"
        echo "function_app_name=${function_app_name}" >> "$GITHUB_OUTPUT"
      working-directory: ./terraform
      env:
        ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

  deploy-function:
    runs-on: ubuntu-latest
    needs: terraform  # Ensures this job runs after the terraform job

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      working-directory: azure_functions

    - name: Archive Function App
      run: zip -r functionapp.zip .
      working-directory: azure_functions

    - name: Install Azure CLI
      run: |
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

    - name: Azure CLI Login
      run: |
        az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}

    - name: Deploy to Azure Function
      run: |
        az functionapp deployment source config-zip -g rg-botgcint-prd -n ${{ needs.terraform.outputs.function_app_name }} --src functionapp.zip
      working-directory: azure_functions
