name: Deploy Terraform

on:
  push:
    paths:
      - '**.tf'
      - '.github/workflows/deploy-terraform.yml'

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0

    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply
      run: terraform apply -auto-approve
      env:
        ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        TF_VAR_member_id: ${{ secrets.MEMBER_ID }}
        TF_VAR_member_pin: ${{ secrets.MEMBER_PIN }}
        TF_VAR_admin_password: ${{ secrets.ADMIN_PASSWORD }}
        TF_VAR_mailchimp_api_key: ${{ secrets.MAILCHIMP_API_KEY }}
