name: Deploy Azure Function

on:
  push:
    branches:
      - main
    paths:
      - 'sync_with_ig.py'
      - 'requirements.txt'
      - '.github/workflows/deploy-function.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Archive Function App
      run: zip -r functionapp.zip .

    - name: Deploy to Azure Function
      uses: azure/functions-action@v1
      with:
        app-name: sync-with-ig-function
        package: functionapp.zip
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
